In [1]:
import main as pf
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
Uganda_population = pf.TargetGroup('Uganda_population', 10)

In [3]:
Uganda_population.n

10

In [4]:
age = pf.State(name='age',
                 transistor= pf.Transistor.add(number=1),
                 generator= tfp.distributions.NegativeBinomial(total_count=100, probs=0.4).sample
                )

In [5]:
Uganda_population.add_state(age)

In [6]:
Uganda_population.next()

In [12]:
Uganda_population.state['age']

{'name': 'age',
 'index': 1,
 'transistor': <function main.Transistor.add.<locals>.returned_add(tensor, tensor_slice_index)>}

In [13]:
Uganda_population.tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([60., 58., 73., 67., 54., 69., 63., 59., 65., 69.], dtype=float32)>

In [14]:
Uganda_population.next()

In [15]:
Uganda_population.tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([61., 59., 74., 68., 55., 70., 64., 60., 66., 70.], dtype=float32)>

In [22]:
Uganda_population.add_state(age)

In [23]:
Uganda_population.state

{'age': {'name': 'age',
  'index': 1,
  'transistor': <function main.Transistor.add.<locals>.returned_add(tensor, tensor_slice_index)>}}

In [24]:
Uganda_population.tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([61., 59., 74., 68., 55., 70., 64., 60., 66., 70.], dtype=float32)>

In [27]:
test = pf.State(name='test',
                 transistor= pf.Transistor.add(number=1),
                 generator= tfp.distributions.NegativeBinomial(total_count=100, probs=0.4).sample
                )

In [28]:
Uganda_population.add_state(test)
Uganda_population.state

{'age': {'name': 'age',
  'index': 1,
  'transistor': <function main.Transistor.add.<locals>.returned_add(tensor, tensor_slice_index)>},
 'test': {'name': 'test',
  'index': 1,
  'transistor': <function main.Transistor.add.<locals>.returned_add(tensor, tensor_slice_index)>}}

In [29]:
Uganda_population.tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([61., 59., 74., 68., 55., 70., 64., 60., 66., 70.], dtype=float32)>

In [31]:
tf.ones()

0