In [1]:
import main as pf
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
Uganda_population = pf.TargetGroup('Uganda_population', 10)

In [3]:
Uganda_population.n

10

In [4]:
age = pf.State(name='age',
                 transistor= pf.Transistor.add(number=1),
                 generator= tfp.distributions.NegativeBinomial(total_count=100, probs=0.4).sample
                )

In [5]:
Uganda_population.add_state(age)

tf.Tensor([79. 56. 62. 77. 83. 56. 67. 62. 69. 48.], shape=(10,), dtype=float32)
tf.Tensor([79. 56. 62. 77. 83. 56. 67. 62. 69. 48.], shape=(10,), dtype=float32)


In [6]:
Uganda_population.tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([66., 67., 70., 64., 53., 60., 64., 69., 83., 71.], dtype=float32)>

tf.Tensor([66. 71. 70. 64. 53. 60. 64. 69. 83. 71.], shape=(10,), dtype=float32)


In [13]:
Uganda_population.tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([54., 85., 56., 64., 42., 73., 74., 64., 65., 92.], dtype=float32)>

In [14]:
for key, value in Uganda_population.state.items():
    print(value['name'])

age


In [17]:
a = tf.constant([79.,56.,62.,77.,83.,56.,67.,62.,69.,48.])
tf.reshape(a, [1, -1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[79., 56., 62., 77., 83., 56., 67., 62., 69., 48.]], dtype=float32)>